// Translations dictionary
const translations = {
    fr: {
        "nav-home": "Accueil",
        "nav-about": "À propos",
        "nav-services": "Services",
        "nav-products": "Équipements",
        "search-placeholder": "Rechercher...",
        "welcome-title": "Bienvenue chez GeometriTech",
        "pro-solutions": "Solutions professionnelles de topographie",
        "pro-solutions-desc": "Nous utilisons des équipements modernes et des outils technologiques avancés afin de garantir une précision optimale pour chaque projet, du levé terrain jusqu'à la conception finale.",
        "creative-style": "Création de style",
        "creative-ideas": "Idées créatives",
        "best-expertise": "Nos meilleures expertises",
        "equipment-title": "Équipements de mesure de haute précision",
        "equipment-desc": "Nous utilisons des récepteurs GNSS, stations totales et instruments de mesure de dernière génération pour garantir des résultats fiables et précis.",
        "expertise-title": "Expertise terrain et technique",
        "expertise-desc": "Notre équipe combine expérience terrain et maîtrise technologique afin d'assurer des levés précis, une analyse rigoureuse des données et une livraison conforme aux exigences du projet..",
        "our-clients": "Nos Clients",
        "client-hokkins": "Un service professionnel, une excellente communication et des résultats conformes aux délais annoncés.",
        "client-louella": "GeometriTech nous a fourni des données topographiques fiables et précises, facilitant la planification et l'exécution de notre projet.",
        "what-we-do": "Ce que nous faisons",
        "complete-solutions": "Des solutions complètes en topographie et géomatique",
        "complete-solutions-desc": "Nous proposons une gamme complète de services allant du levé terrain à la conception technique, en intégrant les technologies modernes et les standards professionnels du secteur.",
        "survey": "Levés topographiques et bornage",
        "implantation": "Implantation et piquetage de construction",
        "data-processing": "Traitement et analyse des données terrain",
        "technical-drawings": "Dessins techniques et plans de site",
        "gnss-solutions": "Solutions technologiques GNSS",
        "contact-title": "Nous contacter",
        "contact-desc": "Vous souhaitez en savoir plus sur GeometriTech ou discuter de votre projet ? Contactez-nous et notre équipe se fera un plaisir de vous accompagner.",
        "form-title": "Contactez-nous",
        "form-name": "Votre nom",
        "form-email": "Votre email",
        "form-message": "Votre message",
        "form-submit": "Envoyer",
        "address-title": "Adresse",
        "whatsapp-message": "Bonjour,%20je%20vous%20contacte%20depuis%20le%20site%20GeometriTech",
        "placeholder-lorem": "Du texte lorem ipsum",
        "lorem-text": "Du texte lorem ipsum placeholder",
        "about-us-title": "À propos de nous",
        "about-mission": "Notre mission et notre expertise",
        "about-mission-desc": "GeometriTech est une entreprise spécialisée en topographie, géomatique et technologies de mesure. Notre mission est de fournir des données précises, fiables et conformes aux normes afin de soutenir les projets de construction, d'ingénierie et de développement foncier. Nous combinons expertise terrain, technologies modernes et méthodes professionnelles pour accompagner nos clients à chaque étape de leurs projets.",
        "about-approach": "Une approche professionnelle et rigoureuse",
        "about-approach-desc": "Chez GeometriTech, nous accordons une importance particulière à la précision, à la transparence et au respect des délais. Chaque projet est traité avec rigueur afin de garantir des résultats exploitables et adaptés aux exigences techniques et réglementaires.",
        "services-concept": "Conception, données & technologies",
        "services-concept-desc": "Nous assurons le traitement des données terrain, l'intégration des informations topographiques et la production de plans techniques exploitables par les professionnels.",
        "equipment-page-title": "Équipements",
        "copyright": "© 2016 GeometriTech. Tous droits réservés | Design par",
        "filter-all": "Tous",
        "filter-topography": "Topographie",
        "filter-geomatics": "Géomatique",
        "filter-cartography": "Cartographie",
        "filter-drone": "Drone & GNSS",
        "product-gnss": "Récepteurs GNSS professionnels",
        "product-gnss-desc": "Récepteurs GNSS multi-constellations conçus pour les levés topographiques de haute précision, compatibles avec les travaux de terrain exigeants.",
        "product-stations": "Stations totales",
        "product-stations-desc": "Stations totales électroniques permettant des mesures précises d'angles et de distances pour les projets de construction et d'implantation.",
        "product-datacollectors": "Collecteurs de données",
        "product-datacollectors-desc": "Terminaux robustes pour la collecte et le stockage des données terrain, compatibles avec les équipements GNSS et stations totales.",
        "product-accessories": "Accessoires de topographie",
        "product-accessories-desc": "Trépieds, mires, supports, batteries et accessoires essentiels pour assurer des opérations terrain efficaces et sécurisées.",
        "product-construction": "Outils de mesure pour la construction",
        "product-construction-desc": "Équipements dédiés à l'implantation, au piquetage et au contrôle des travaux de construction.",
        "product-software": "Logiciels de topographie et de conception",
        "product-software-desc": "Solutions logicielles pour le traitement des données topographiques, la modélisation, la cartographie et la production de plans techniques.",
        "why-choose-title": "Pourquoi nous choisir",
        "why-expertise": "Expertise professionnelle",
        "why-expertise-desc": "Une équipe qualifiée avec une solide expérience en topographie et géomatique.",
        "why-technology": "Technologies modernes",
        "why-technology-desc": "Utilisation d'équipements GNSS, stations totales et logiciels spécialisés de dernière génération.",
        "why-reliability": "Fiabilité et conformité",
        "why-reliability-desc": "Des travaux conformes aux normes professionnelles et aux exigences réglementaires.",
        "why-deadlines": "Respect des délais",
        "why-deadlines-desc": "Planification rigoureuse et livraisons dans les délais convenus.",
        "why-support": "Accompagnement client",
        "why-support-desc": "Un suivi personnalisé et une communication claire tout au long du projet.",
        "why-complete": "Solutions complètes",
        "why-complete-desc": "De la collecte des données terrain à la conception finale des plans.",
        "team-title": "Notre équipe",
        "team-john": "Professionnel qualifié spécialisé en topographie et technologies de mesure, engagé à fournir des résultats précis et fiables.",
        "services-title": "Nos Services",
        "service-surveying": "Services de topographie",
        "service-surveying-desc": "Nous fournissons des services complets de topographie destinés aux projets de construction, d'ingénierie et de développement foncier.Nos levés sont réalisés avec précision et conformément aux normes professionnelles en vigueur.",
        "stats-projects": "Projets réalisés",
        "stats-studies": "Études complétées",
        "stats-hours": "Heures de terrain",
        "stats-clients": "Clients accompagnés",
        "advantages-title": "Nos avantages",
        "adv-precision": "Précision et conformité",
        "adv-precision-desc": "Des levés précis, réalisés avec des équipements modernes et conformes aux exigences réglementaires.",
        "adv-technology": "Technologies de pointe",
        "adv-technology-desc": "Utilisation de récepteurs GNSS, stations totales et logiciels spécialisés pour des résultats fiables.",
        "adv-support": "Accompagnement professionnel",
        "adv-support-desc": "Un suivi rigoureux, une communication claire et un respect strict des délais.",
        "contact-freephone": "Téléphone gratuit",
        "contact-telephone": "Téléphone",
        "contact-fax": "Fax",
        "contact-email": "E-mail"
    },
    en: {
        "nav-home": "Home",
        "nav-about": "About",
        "nav-services": "Services",
        "nav-products": "Equipment",
        "search-placeholder": "Search...",
        "welcome-title": "Welcome to GeometriTech",
        "pro-solutions": "Professional surveying solutions",
        "pro-solutions-desc": "We use modern equipment and advanced technological tools to guarantee optimal precision for every project, from field survey to final design.",
        "creative-style": "Style creation",
        "creative-ideas": "Creative ideas",
        "best-expertise": "Our best expertise",
        "equipment-title": "High precision measurement equipment",
        "equipment-desc": "We use GNSS receivers, total stations and latest generation measurement instruments to guarantee reliable and accurate results.",
        "expertise-title": "Field and technical expertise",
        "expertise-desc": "Our team combines field experience and technological mastery to ensure accurate surveys, rigorous data analysis and delivery in compliance with project requirements..",
        "our-clients": "Our Clients",
        "client-hokkins": "Professional service, excellent communication and results delivered on schedule.",
        "client-louella": "GeometriTech provided us with reliable and accurate topographic data, facilitating the planning and execution of our project.",
        "what-we-do": "What we do",
        "complete-solutions": "Complete surveying and geomatics solutions",
        "complete-solutions-desc": "We offer a complete range of services from field survey to technical design, integrating modern technologies and professional industry standards.",
        "survey": "Topographic surveys and boundary marking",
        "implantation": "Construction implantation and staking",
        "data-processing": "Data processing and field analysis",
        "technical-drawings": "Technical drawings and site plans",
        "gnss-solutions": "GNSS technological solutions",
        "contact-title": "Contact Us",
        "contact-desc": "Want to learn more about GeometriTech or discuss your project? Contact us and our team will be happy to help you.",
        "form-title": "Contact Us",
        "form-name": "Your name",
        "form-email": "Your email",
        "form-message": "Your message",
        "form-submit": "Send",
        "address-title": "Address",
        "whatsapp-message": "Hello,%20I%20am%20contacting%20you%20from%20the%20GeometriTech%20website",
        "placeholder-lorem": "Some lorem ipsum text",
        "lorem-text": "Lorem ipsum placeholder text",
        "about-us-title": "About Us",
        "about-mission": "Our mission and expertise",
        "about-mission-desc": "GeometriTech is a company specializing in surveying, geomatics and measurement technologies. Our mission is to provide accurate, reliable data compliant with standards to support construction, engineering and land development projects. We combine field expertise, modern technologies and professional methods to support our clients at every stage of their projects.",
        "about-approach": "A professional and rigorous approach",
        "about-approach-desc": "At GeometriTech, we place particular emphasis on precision, transparency and respecting deadlines. Each project is treated with rigor to ensure results that are usable and adapted to technical and regulatory requirements.",
        "services-concept": "Design, data & technologies",
        "services-concept-desc": "We handle field data processing, integration of topographic information and production of technical plans that can be used by professionals.",
        "equipment-page-title": "Equipment",
        "copyright": "© 2016 GeometriTech. All rights reserved | Design by",
        "filter-all": "All",
        "filter-topography": "Topography",
        "filter-geomatics": "Geomatics",
        "filter-cartography": "Cartography",
        "filter-drone": "Drone & GNSS",
        "product-gnss": "Professional GNSS receivers",
        "product-gnss-desc": "Multi-constellation GNSS receivers designed for high-precision topographic surveys, compatible with demanding field work.",
        "product-stations": "Total stations",
        "product-stations-desc": "Electronic total stations for precise angle and distance measurements for construction and implantation projects.",
        "product-datacollectors": "Data collectors",
        "product-datacollectors-desc": "Rugged terminals for field data collection and storage, compatible with GNSS equipment and total stations.",
        "product-accessories": "Surveying accessories",
        "product-accessories-desc": "Tripods, leveling rods, supports, batteries and essential accessories to ensure efficient and safe field operations.",
        "product-construction": "Construction measurement tools",
        "product-construction-desc": "Equipment dedicated to implantation, staking and inspection of construction work.",
        "product-software": "Surveying and design software",
        "product-software-desc": "Software solutions for processing topographic data, modeling, mapping and producing technical plans.",
        "why-choose-title": "Why choose us",
        "why-expertise": "Professional expertise",
        "why-expertise-desc": "A qualified team with solid experience in surveying and geomatics.",
        "why-technology": "Modern technologies",
        "why-technology-desc": "Use of GNSS equipment, total stations and specialized software of the latest generation.",
        "why-reliability": "Reliability and compliance",
        "why-reliability-desc": "Work compliant with professional standards and regulatory requirements.",
        "why-deadlines": "Respect for deadlines",
        "why-deadlines-desc": "Rigorous planning and deliveries within agreed timelines.",
        "why-support": "Customer support",
        "why-support-desc": "Personalized follow-up and clear communication throughout the project.",
        "why-complete": "Complete solutions",
        "why-complete-desc": "From field data collection to final plan design.",
        "team-title": "Our team",
        "team-john": "Qualified professional specializing in surveying and measurement technologies, committed to providing accurate and reliable results.",
        "services-title": "Our Services",
        "service-surveying": "Surveying services",
        "service-surveying-desc": "We provide comprehensive surveying services for construction, engineering and land development projects. Our surveys are conducted with precision and in compliance with professional standards.",
        "stats-projects": "Projects completed",
        "stats-studies": "Studies completed",
        "stats-hours": "Field hours",
        "stats-clients": "Clients supported",
        "advantages-title": "Our advantages",
        "adv-precision": "Precision and compliance",
        "adv-precision-desc": "Precise surveys, conducted with modern equipment and compliant with regulatory requirements.",
        "adv-technology": "Cutting-edge technologies",
        "adv-technology-desc": "Use of GNSS receivers, total stations and specialized software for reliable results.",
        "adv-support": "Professional support",
        "adv-support-desc": "Rigorous follow-up, clear communication and strict adherence to deadlines.",
        "contact-freephone": "Free phone",
        "contact-telephone": "Telephone",
        "contact-fax": "Fax",
        "contact-email": "E-mail"
    },
    ht: {
        "nav-home": "Akèy",
        "nav-about": "Sou nou",
        "nav-services": "Sèvis",
        "nav-products": "Ekipman",
        "search-placeholder": "Chèche...",
        "welcome-title": "Byenveni nan GeometriTech",
        "pro-solutions": "Solisyon siveyman pwofesyonel",
        "pro-solutions-desc": "Nou itilize ekipman modèn ak zouti teknoloji avanse pou garanti presizyon optimal pou chak pwojè, soti nan siveyman tèren jiska dizen final.",
        "creative-style": "Kreyasyon stil",
        "creative-ideas": "Lide kreyatif",
        "best-expertise": "Ekspèriz nou yo pi bon",
        "equipment-title": "Ekipman mezi presizyon wo",
        "equipment-desc": "Nou itilize reseptè GNSS, estasyon total ak enstriman mezi dènye jenerasyon pou garanti rezilta fyab ak egzak.",
        "expertise-title": "Ekspèriz tèren ak teknik",
        "expertise-desc": "Ekip nou konbine eksperyans tèren ak mètrize teknoloji pou asire siveyman egzak, analiz rijid done ak delivrans ki konfòm ak egzijans pwojè.",
        "our-clients": "Kliyè nou yo",
        "client-hokkins": "Sèvis pwofesyonel, bon kominikasyon ak rezilta ki delivre sou orè.",
        "client-louella": "GeometriTech bay nou done topografik fyab ak egzak, fasilitan planifikasyon ak egzekisyon pwojè nou.",
        "what-we-do": "Kisa nou fè",
        "complete-solutions": "Solisyon siveyman ak jeomatik konplè",
        "complete-solutions-desc": "Nou ofri yon seri sèvis konplè soti nan siveyman tèren jiska dizen teknik, entegre teknoloji modèn ak estanda endistri pwofesyonel.",
        "survey": "Siveyman topografik ak mak fwontyè",
        "implantation": "Implantasyon konstriksyon ak pik",
        "data-processing": "Pwosè done ak analiz tèren",
        "technical-drawings": "Desen teknik ak plan sit",
        "gnss-solutions": "Solisyon teknoloji GNSS",
        "contact-title": "Kontakte nou",
        "contact-desc": "Eske ou vle aprann plis sou GeometriTech oswa diskite sou pwojè ou? Kontakte nou e ekip nou a ap kontan yo ede ou.",
        "form-title": "Kontakte nou",
        "form-name": "Non ou",
        "form-email": "Imèl ou",
        "form-message": "Mesaj ou",
        "form-submit": "Voye",
        "address-title": "Adrès",
        "whatsapp-message": "Bonjou,%20mwen%20kontakte%20ou%20nan%20sit%20GeometriTech",
        "placeholder-lorem": "Kèk tèks lorem ipsum",
        "lorem-text": "Kèk tèks lorem ipsum placeholder",
        "about-us-title": "Sou nou",
        "about-mission": "Misyon nou ak ekspèriz nou",
        "about-mission-desc": "GeometriTech se yon konpani espesyalize nan siveyman, jeomatik ak teknoloji mezi. Misyon nou se bay done egzak, fyab ak konfòm ak nòm pou sipòte pwojè konstriksyon, jeni ak devlopman tèren. Nou konbine ekspèriz tèren, teknoloji modèn ak metòd pwofesyonel pou sipòte kliyè nou nan chak etap pwojè yo.",
        "about-approach": "Yon apwòch pwofesyonel ak rijid",
        "about-approach-desc": "Nan GeometriTech, nou akòde enpòtans patikilyè a presizyon, transparans ak respè dèlè. Chak pwojè trete ak rigidite pou garanti rezilta ekspwoatabl ak adapte a egzijans teknik ak reglemantè.",
        "services-concept": "Desen, done & teknoloji",
        "services-concept-desc": "Nou asire pwosè done tèren, entegrasyon enfòmasyon topografik ak produksyon plan teknik ekspwoatabl pa pwofesyonel.",
        "equipment-page-title": "Ekipman",
        "copyright": "© 2016 GeometriTech. Tout dwa rezève | Desen pa",
        "filter-all": "Tout",
        "filter-topography": "Topografi",
        "filter-geomatics": "Jeomatik",
        "filter-cartography": "Katografi",
        "filter-drone": "Drone & GNSS",
        "product-gnss": "Reseptè GNSS pwofesyonel",
        "product-gnss-desc": "Reseptè GNSS milti-konstelayon desine pou siveyman topografik presizyon wo, konpatib ak travay tèren egzijan.",
        "product-stations": "Estasyon total",
        "product-stations-desc": "Estasyon total elektwonik pou mezi ang egzak ak distans pou pwojè konstriksyon ak implantasyon.",
        "product-datacollectors": "Kolektè done",
        "product-datacollectors-desc": "Tèminal tèf pou koleksyon done tèren ak depo, konpatib ak ekipman GNSS ak estasyon total.",
        "product-accessories": "Akseswa siveyman",
        "product-accessories-desc": "Trepyè, baren nivo, sipò, batri ak akseswa esansyel pou asire operasyon tèren efikas ak sekirize.",
        "product-construction": "Zouti mezi konstriksyon",
        "product-construction-desc": "Ekipman dediye pou implantasyon, pik ak enspeksyon travay konstriksyon.",
        "product-software": "Logisyèl siveyman ak dizen",
        "product-software-desc": "Solisyon logisyèl pou pwosè done topografik, modèlizasyon, makartografi ak produksyon plan teknik.",
        "why-choose-title": "Poukisa chwazi nou",
        "why-expertise": "Ekspèriz pwofesyonel",
        "why-expertise-desc": "Yon ekip kalifiye ak eksperyans solid nan siveyman ak jeomatik.",
        "why-technology": "Teknoloji modèn",
        "why-technology-desc": "Itilizasyon ekipman GNSS, estasyon total ak logisyèl espesyalize dènye jenerasyon.",
        "why-reliability": "Fiabilite ak konformite",
        "why-reliability-desc": "Travay konpliyans ak estanda pwofesyonel ak egzijans regilatori.",
        "why-deadlines": "Respè pou daten",
        "why-deadlines-desc": "Planifikasyon rijid ak delivrans nan tèm akò.",
        "why-support": "Sipò kliyan",
        "why-support-desc": "Swiv pèsonalize ak kominikasyon kle alantou tout pwojè.",
        "why-complete": "Solisyon konplè",
        "why-complete-desc": "Soti nan koleksyon done tèren jiska dizen final plan.",
        "team-title": "Ekip nou",
        "team-john": "Pwofesyonel kalifiye espesyalize nan siveyman ak teknoloji mezi, komite bay rezilta presizyon ak fyab.",
        "services-title": "Sèvis nou",
        "service-surveying": "Sèvis siveyman",
        "service-surveying-desc": "Nou bay sèvis siveyman konprehansif pou pwojè konstriksyon, jeni ak devlopman tèren. Siveyman nou yo fè ak presizyon ak konformite ak estanda pwofesyonel.",
        "stats-projects": "Pwojè konplete",
        "stats-studies": "Etid konplete",
        "stats-hours": "Zè tèren",
        "stats-clients": "Kliyan sipòte",
        "advantages-title": "Avantaj nou",
        "adv-precision": "Presizyon ak konformite",
        "adv-precision-desc": "Siveyman presizyon, fè ak ekipman modèn ak konpliyans ak egzijans regilatori.",
        "adv-technology": "Teknoloji fwa",
        "adv-technology-desc": "Itilizasyon reseptè GNSS, estasyon total ak logisyèl espesyalize pou rezilta fyab.",
        "adv-support": "Sipò pwofesyonel",
        "adv-support-desc": "Swiv rijid, kominikasyon kle ak respè strict pou daten.",
        "contact-freephone": "Telepòn gratis",
        "contact-telephone": "Telepòn",
        "contact-fax": "Faks",
        "contact-email": "E-mail"
    }
};

// Get current language from localStorage or default to French
function getCurrentLanguage() {
    return localStorage.getItem('selectedLanguage') || 'fr';
}

// Change language
function changeLanguage(lang) {
    localStorage.setItem('selectedLanguage', lang);
    applyTranslations(lang);
}

// Apply translations to the page
function applyTranslations(lang) {
    // Update language selector
    const selector = document.getElementById('languageSwitch');
    if (selector) {
        selector.value = lang;
    }

    // Update all translatable elements
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            // Check if it's an input or textarea
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[lang][key];
                // Preserve the current value if it's empty or the placeholder
                if (!element.value || element.value === element.getAttribute('data-original-placeholder')) {
                    element.setAttribute('data-original-placeholder', translations[lang][key]);
                }
            } else {
                // For other elements, update the text content
                element.textContent = translations[lang][key];
            }
        }
    });

    // Update href for WhatsApp button
    const whatsappLink = document.querySelector('.whatsapp-float a');
    if (whatsappLink) {
        const message = translations[lang]["whatsapp-message"];
        whatsappLink.href = `https://wa.me/50944465292?text=${message}`;
    }

    // Store language preference
    document.documentElement.lang = lang;
}

// Initialize on page load
document.addEventListener('DOMContentLoaded', function() {
    const currentLang = getCurrentLanguage();
    applyTranslations(currentLang);
});
